"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"
import { Panel } from "@/components/science/tool-page"

const field = "h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary"
function NumberField({ label, value, onChange, step = "any" }: { label: string; value: number; onChange: (value: number) => void; step?: string }) { return <label className="grid gap-1.5 text-xs text-muted-foreground">{label}<input className={field} type="number" step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label> }
function Readout({ label, value, unit = "" }: { label: string; value: string | number; unit?: string }) { return <div className="rounded-lg border border-border bg-muted/40 p-3"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-mono text-lg">{value} <span className="text-xs text-muted-foreground">{unit}</span></p></div> }

export function PhysicsLaboratory() {
  const [velocity, setVelocity] = React.useState(20), [angle, setAngle] = React.useState(45), [height, setHeight] = React.useState(0), [gravity, setGravity] = React.useState(9.81), [running, setRunning] = React.useState(false), [time, setTime] = React.useState(0)
  React.useEffect(() => { if (!running) return; const id = window.setInterval(() => setTime((t) => t + 0.04), 40); return () => window.clearInterval(id) }, [running])
  const rad = angle * Math.PI / 180, vx = velocity * Math.cos(rad), vy = velocity * Math.sin(rad), flight = (vy + Math.sqrt(vy * vy + 2 * gravity * height)) / gravity, maxHeight = height + vy * vy / (2 * gravity), range = vx * flight, y = Math.max(0, height + vy * time - 0.5 * gravity * time * time)
  return <div className="flex flex-col gap-6"><div><h1 className="text-3xl font-semibold tracking-tight">Physics laboratory</h1><p className="mt-2 max-w-2xl leading-7 text-muted-foreground">Run real-time mechanics experiments. Change a parameter, then play, pause, or reset the projectile and inspect the computed model.</p></div><div className="grid gap-6 lg:grid-cols-[1fr_320px]"><Panel title="Projectile motion"><div className="relative min-h-[360px] overflow-hidden rounded-xl border border-border bg-slate-950"><div className="absolute inset-x-0 bottom-8 border-t border-cyan-200/20" /><div className="absolute bottom-8 left-8 size-4 rounded-full bg-amber-300 shadow-[0_0_20px_rgba(253,224,71,.8)]" style={{ transform: `translate(${Math.min(92, (Math.max(0, Math.min(time, flight)) / Math.max(flight, 0.01)) * 82)}%, -${Math.min(72, (y / Math.max(maxHeight, 1)) * 62)}%)` }} /><svg className="absolute inset-0 h-full w-full opacity-45" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M 8 92 Q 45 8 90 92" fill="none" stroke="currentColor" strokeDasharray="1 2" className="text-cyan-200" /></svg><div className="absolute left-4 top-4 font-mono text-xs text-cyan-100">t = {Math.min(time, flight).toFixed(2)} s</div></div><div className="mt-4 flex gap-2"><Button onClick={() => setRunning((v) => !v)}>{running ? "Pause" : "Play"}</Button><Button variant="outline" onClick={() => { setRunning(false); setTime(0) }}>Reset</Button></div></Panel><Panel title="Experiment controls"><div className="grid gap-4"><NumberField label="Initial velocity (m/s)" value={velocity} onChange={setVelocity} /><NumberField label="Launch angle (degrees)" value={angle} onChange={setAngle} /><NumberField label="Initial height (m)" value={height} onChange={setHeight} /><NumberField label="Gravity (m/s²)" value={gravity} onChange={setGravity} step="0.01" /></div><div className="mt-5 grid grid-cols-2 gap-2"><Readout label="Horizontal velocity" value={vx.toFixed(2)} unit="m/s" /><Readout label="Vertical velocity" value={vy.toFixed(2)} unit="m/s" /><Readout label="Maximum height" value={maxHeight.toFixed(2)} unit="m" /><Readout label="Range" value={range.toFixed(2)} unit="m" /><Readout label="Flight time" value={flight.toFixed(2)} unit="s" /><Readout label="Acceleration" value={gravity.toFixed(2)} unit="m/s²" /></div></Panel></div></div>
}

const biologyParts = [{ name: "Nucleus", function: "Stores DNA and coordinates gene expression." }, { name: "Mitochondria", function: "Generate ATP through cellular respiration." }, { name: "Ribosomes", function: "Translate mRNA into proteins." }, { name: "Golgi apparatus", function: "Modifies, sorts, and ships proteins." }, { name: "Cell membrane", function: "Controls exchange between the cell and its environment." }, { name: "Lysosome", function: "Breaks down macromolecules and cellular waste." }]
export function BiologyLaboratory() { const [selected, setSelected] = React.useState(biologyParts[0]); const [plant, setPlant] = React.useState(false); return <div className="flex flex-col gap-6"><div><h1 className="text-3xl font-semibold tracking-tight">Biology laboratory</h1><p className="mt-2 max-w-2xl leading-7 text-muted-foreground">Inspect a living cell by selecting structures. The model is a functional learning surface: each target updates the explanation panel and the plant toggle changes the organelle set.</p></div><div className="flex gap-2"><Button variant={!plant ? "default" : "outline"} onClick={() => setPlant(false)}>Animal cell</Button><Button variant={plant ? "default" : "outline"} onClick={() => setPlant(true)}>Plant cell</Button></div><div className="grid gap-6 lg:grid-cols-[1fr_320px]"><Panel title={plant ? "Plant cell model" : "Animal cell model"}><div className="relative mx-auto aspect-square max-w-[480px] rounded-[42%] border-4 border-emerald-300/50 bg-emerald-300/10 p-10"><div className="flex h-full flex-wrap content-center justify-center gap-3 rounded-[40%] border border-emerald-200/30 bg-emerald-200/5 p-8">{(plant ? [...biologyParts, { name: "Chloroplast", function: "Capture light energy for photosynthesis." }, { name: "Cell wall", function: "Provides rigid structural support." }, { name: "Central vacuole", function: "Stores water and maintains turgor pressure." }] : biologyParts).map((part, index) => <button key={part.name} onClick={() => setSelected(part)} className={`rounded-full border px-3 py-2 text-xs transition ${selected.name === part.name ? "border-cyan-200 bg-cyan-200/20 text-cyan-100" : "border-border bg-background/50 hover:border-primary"}`} style={{ transform: `rotate(${index * 7 - 20}deg)` }}>{part.name}</button>)}</div></div></Panel><Panel title="Structure information"><p className="font-mono text-xs uppercase tracking-widest text-primary">Selected organelle</p><h2 className="mt-3 text-2xl font-semibold">{selected.name}</h2><p className="mt-4 leading-7 text-muted-foreground">{selected.function}</p><div className="mt-6 grid gap-2"><Readout label="Model" value={plant ? "Plant cell" : "Animal cell"} /><Readout label="Interaction" value="Click organelles" /></div></Panel></div></div> }
