"use client"

import * as React from "react"
import { balanceEquation } from "@/lib/science/chem/equation-balancer"
import { strongAcidPh, strongBasePh, weakAcidPh, weakBasePh, titrationPh } from "@/lib/science/chem/acid-base"
import { MOLECULES } from "@/lib/science/data/molecules"
import { Button } from "@/components/ui/button"

const inputClass = "h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary"

export function ToolPage({ title, eyebrow, description, children }: { title: string; eyebrow: string; description: string; children?: React.ReactNode }) {
  return <main className="mx-auto flex w-full max-w-7xl flex-col gap-8 px-5 py-8 md:px-8"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-3 text-balance text-4xl font-semibold tracking-tight md:text-5xl">{title}</h1><p className="mt-4 text-pretty leading-7 text-muted-foreground">{description}</p></div>{children}</main>
}

export function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="font-mono text-xs uppercase tracking-[0.16em] text-muted-foreground">{title}</h2><div className="mt-5">{children}</div></section> }

export function EquationTool() {
  const [equation, setEquation] = React.useState("Fe + O2 -> Fe2O3")
  const [result, setResult] = React.useState(() => balanceEquation(equation))
  return <ToolPage eyebrow="Chemistry / calculations" title="Equation balancer" description="Turn an unbalanced reaction into the smallest whole-number coefficients using exact stoichiometric linear algebra."><Panel title="Reaction input"><div className="flex flex-col gap-3 md:flex-row"><input aria-label="Chemical equation" className={inputClass} value={equation} onChange={(e) => setEquation(e.target.value)} /><Button onClick={() => setResult(balanceEquation(equation))}>Balance reaction</Button></div>{result.error ? <p className="mt-4 text-sm text-destructive">{result.error}</p> : <div className="mt-6 rounded-xl bg-muted/50 p-5 text-center font-mono text-lg">{result.reactants.map((x) => `${x.coefficient === 1 ? "" : x.coefficient}${x.formula}`).join(" + ")} → {result.products.map((x) => `${x.coefficient === 1 ? "" : x.coefficient}${x.formula}`).join(" + ")}</div>}</Panel></ToolPage>
}

export function AcidBaseTool() {
  const [kind, setKind] = React.useState("acid")
  const [concentration, setConcentration] = React.useState("0.1")
  const [result, setResult] = React.useState(() => strongAcidPh(0.1))
  function calculate() { const c = Number(concentration); if (!Number.isFinite(c) || c <= 0) return; setResult(kind === "acid" ? strongAcidPh(c) : strongBasePh(c)) }
  return <ToolPage eyebrow="Chemistry / equilibrium" title="Acid-base lab" description="Explore pH, hydroxide concentration, and the effect of strong acid or base concentration at 25°C."><Panel title="Solution model"><div className="grid gap-4 md:grid-cols-3"><select className={inputClass} value={kind} onChange={(e) => setKind(e.target.value)}><option value="acid">Strong acid</option><option value="base">Strong base</option></select><input className={inputClass} type="number" min="0.000001" step="any" value={concentration} onChange={(e) => setConcentration(e.target.value)} aria-label="Concentration in molar" /><Button onClick={calculate}>Calculate pH</Button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="pH" value={result.pH.toFixed(3)} /><Metric label="pOH" value={result.pOH.toFixed(3)} /><Metric label="Classification" value={result.classification} /></div></Panel></ToolPage>
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-muted/40 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold capitalize">{value}</p></div> }

export function MolecularTool({ bonding = false }: { bonding?: boolean }) { const [selected, setSelected] = React.useState(MOLECULES[0]); return <ToolPage eyebrow="Chemistry / molecular structure" title={bonding ? "Bonding & Lewis structures" : "Molecular viewer"} description={bonding ? "Compare bond order, geometry, polarity, and idealized Lewis-style structure data." : "Inspect idealized 3D molecular presets with geometry and polarity annotations."}><div className="grid gap-6 lg:grid-cols-[280px_1fr]"><Panel title="Molecule library"><div className="flex flex-col gap-2">{MOLECULES.slice(0, 10).map((m) => <button key={m.formula} onClick={() => setSelected(m)} className={`rounded-lg px-3 py-3 text-left text-sm transition-colors ${selected.formula === m.formula ? "bg-primary text-primary-foreground" : "hover:bg-muted"}`}><span className="font-mono">{m.formula}</span><span className="ml-2 opacity-70">{m.name}</span></button>)}</div></Panel><Panel title="Selected structure"><div className="grid gap-4 sm:grid-cols-2"><Metric label="Compound" value={selected.name} /><Metric label="Formula" value={selected.formula} /><Metric label="Geometry" value={selected.geometry} /><Metric label="Polarity" value={selected.polarity} /></div><p className="mt-5 leading-7 text-muted-foreground">{selected.description}</p><div className="mt-5 rounded-xl bg-muted/50 p-4 font-mono text-sm">{selected.atoms.map((a, i) => `${i + 1}: ${a.element}  `).join("")}<br />Bonds: {selected.bonds.map((b) => `${b.order}×`).join(" ")}</div></Panel></div></ToolPage> }

export function AssistantTool() { const [prompt, setPrompt] = React.useState(""); const [answer, setAnswer] = React.useState("Ask about an element, reaction, or concept to begin."); function ask() { if (prompt.trim()) setAnswer(`Academia notes: ${prompt.trim()} is ready for exploration. Open a dedicated lab from the sidebar for calculations and interactive data.`) } return <ToolPage eyebrow="Academia / guide" title="AI science assistant" description="A focused study companion for navigating the Academia laboratory. This local preview keeps your questions in the browser and points you toward the right tool."><Panel title="Ask Academia"><textarea className="min-h-32 w-full resize-y rounded-lg border border-border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-primary" placeholder="e.g. Why is water bent?" value={prompt} onChange={(e) => setPrompt(e.target.value)} /><div className="mt-3 flex justify-end"><Button onClick={ask}>Explore answer</Button></div><div className="mt-5 rounded-xl bg-muted/50 p-5 leading-7 text-muted-foreground">{answer}</div></Panel></ToolPage> }

export function ConcentrationTool() { const [moles, setMoles] = React.useState("0.5"); const [volume, setVolume] = React.useState("2"); const molarity = Number(moles) / Number(volume); return <ToolPage eyebrow="Chemistry / solutions" title="Concentration lab" description="Calculate molarity from amount of solute and solution volume. Units are moles and liters."><Panel title="Molarity"><div className="grid gap-4 md:grid-cols-3"><input className={inputClass} type="number" value={moles} onChange={(e) => setMoles(e.target.value)} aria-label="Moles" placeholder="Moles" /><input className={inputClass} type="number" value={volume} onChange={(e) => setVolume(e.target.value)} aria-label="Liters" placeholder="Liters" /><Metric label="Molarity" value={Number.isFinite(molarity) ? `${molarity.toFixed(3)} M` : "—"} /></div></Panel></ToolPage> }

export function StoichiometryTool() { return <ToolPage eyebrow="Chemistry / calculations" title="Stoichiometry" description="A guided workspace for mole ratios, mass conversions, and limiting-reagent reasoning."><Panel title="Workflow"><div className="grid gap-4 md:grid-cols-3"><Metric label="Step 1" value="Balance" /><Metric label="Step 2" value="Convert to moles" /><Metric label="Step 3" value="Compare ratios" /></div><p className="mt-5 text-sm leading-6 text-muted-foreground">Start with the Equation Balancer, then use the coefficients as mole ratios. This guided view is ready for the next calculation input.</p></Panel></ToolPage> }

export function TrendsTool() { return <ToolPage eyebrow="Chemistry / data" title="Periodic trends" description="Compare how elemental properties change across periods and down groups. Select an element from the periodic table to inspect its context."><Panel title="Trend map"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Atomic radius" value="↓ across, ↑ down" /><Metric label="Ionization energy" value="↑ across, ↓ down" /><Metric label="Electronegativity" value="↑ across, ↓ down" /></div></Panel></ToolPage> }

export function SubjectPage({ subject, icon, description }: { subject: string; icon: string; description: string }) { return <ToolPage eyebrow="Academia / in development" title={subject} description={description}><div className="rounded-2xl border border-dashed border-border bg-card p-8"><div className="text-5xl" aria-hidden="true">{icon}</div><h2 className="mt-5 text-2xl font-semibold">A new laboratory is taking shape</h2><p className="mt-3 max-w-xl leading-7 text-muted-foreground">The Academia shell is ready for datasets, simulations, and visual experiments in {subject.toLowerCase()}. Use Chemistry to explore the fully available tools today.</p></div></ToolPage> }

export function SimulationTool() { const [volume, setVolume] = React.useState(50); return <ToolPage eyebrow="Chemistry / simulation" title="Interactive simulations" description="A lightweight virtual lab surface for observing concentration changes as solvent volume changes."><Panel title="Dilution experiment"><input className="w-full accent-primary" type="range" min="10" max="100" value={volume} onChange={(e) => setVolume(Number(e.target.value))} aria-label="Solution volume" /><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Volume" value={`${volume} mL`} /><Metric label="Relative concentration" value={`${(50 / volume * 100).toFixed(0)}%`} /><Metric label="Observation" value={volume > 50 ? "Diluted" : "Concentrated"} /></div></Panel></ToolPage> }

export function TitrationTool() { const [volume, setVolume] = React.useState(25); const ph = titrationPh(0.1, 25, 0.1, volume); return <ToolPage eyebrow="Chemistry / equilibrium" title="Titration curve" description="Model a strong acid–strong base titration and inspect the pH around equivalence."><Panel title="Titrant volume"><input className="w-full accent-primary" type="range" min="0" max="50" value={volume} onChange={(e) => setVolume(Number(e.target.value))} aria-label="Base volume added" /><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Base added" value={`${volume} mL`} /><Metric label="pH" value={ph.toFixed(2)} /><Metric label="Region" value={volume < 25 ? "Acid excess" : volume > 25 ? "Base excess" : "Equivalence"} /></div></Panel></ToolPage> }

export function PhysicsPage() { return <SubjectPage subject="Physics" icon="∿" description="Model motion, fields, energy, and waves through clear visual experiments." /> }
export function BiologyPage() { return <SubjectPage subject="Biology" icon="◌" description="Explore cells, genetics, ecology, and living systems through interactive learning modules." /> }
export function SimulationLanding() { return <SimulationTool /> }
export function BufferTool() { const result = weakAcidPh(0.1, 1.8e-5); return <ToolPage eyebrow="Chemistry / equilibrium" title="Buffer study" description="Explore weak-acid equilibrium and the relationship between concentration, Ka, and pH."><Panel title="Acetic acid preset"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Ka" value="1.8 × 10⁻⁵" /><Metric label="Concentration" value="0.100 M" /><Metric label="pH" value={result.pH.toFixed(3)} /></div></Panel></ToolPage> }
export { weakBasePh }
