export type Sample = { t: number; x: number; v: number; energy?: number }
export const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, Number.isFinite(value) ? value : min))
export const projectile = (v0: number, angleDeg: number, height: number, g: number, t: number) => { const a = angleDeg * Math.PI / 180; const vx = v0 * Math.cos(a); const vy = v0 * Math.sin(a); const flight = (vy + Math.sqrt(vy * vy + 2 * g * Math.max(0, height))) / g; return { x: vx * t, y: Math.max(0, height + vy * t - 0.5 * g * t * t), vx, vy, flight, maxHeight: height + vy * vy / (2 * g) } }
export const collision = (m1: number, v1: number, m2: number, v2: number, restitution: number) => ({ v1f: (m1 * v1 + m2 * v2 - m2 * restitution * (v1 - v2)) / (m1 + m2), v2f: (m1 * v1 + m2 * v2 + m1 * restitution * (v1 - v2)) / (m1 + m2) })
export const density = (mass: number, volume: number) => mass / Math.max(volume, 1e-9)
export const buoyancy = (mass: number, volume: number, fluidDensity: number, g = 9.81) => { const objectDensity = density(mass, volume); const submerged = clamp(objectDensity / fluidDensity, 0, 1); return { objectDensity, submerged, buoyantForce: fluidDensity * g * volume * submerged, weight: mass * g, floats: objectDensity < fluidDensity } }
export const springStep = (x: number, v: number, mass: number, k: number, damping: number, dt: number) => { const a = (-k * x - damping * v) / mass; const nextV = v + a * dt; return { x: x + nextV * dt, v: nextV, energy: 0.5 * k * x * x + 0.5 * mass * nextV * nextV } }
export const pendulumStep = (theta: number, omega: number, length: number, g: number, dt: number) => { const nextOmega = omega - (g / length) * Math.sin(theta) * dt; return { theta: theta + nextOmega * dt, omega: nextOmega } }
export const seriesPath = (samples: Sample[], key: keyof Sample, width = 560, height = 150) => { if (!samples.length) return ''; const values = samples.map((s) => Number(s[key] ?? 0)); const min = Math.min(...values), max = Math.max(...values); return samples.map((s, i) => { const x = i / Math.max(samples.length - 1, 1) * width; const y = height - ((Number(s[key] ?? 0) - min) / Math.max(max - min, 1e-9)) * (height - 12) - 6; return `${i ? 'L' : 'M'} ${x.toFixed(1)} ${y.toFixed(1)}` }).join(' ') }
export const fmt = (n: number, digits = 2) => Number.isFinite(n) ? n.toFixed(digits) : '—'
export const sample = (fn: (t: number, previous: Sample) => Sample, duration = 8, dt = 0.05): Sample[] => { const out: Sample[] = []; let previous: Sample = { t: 0, x: 0, v: 0 }; for (let t = 0; t <= duration; t += dt) { previous = fn(t, previous); out.push(previous) } return out }
export const physicsConstants = { g: 9.81, waterDensity: 1000 }
export type LabId = 'density' | 'collision' | 'buoyancy' | 'spring' | 'pendulum'
export const labs: { id: LabId; name: string; subtitle: string; symbol: string }[] = [{ id: 'density', name: 'Density & Material', subtitle: 'Mass, volume, and material identity', symbol: 'ρ' }, { id: 'collision', name: 'Collision', subtitle: 'Momentum and impulse', symbol: '↔' }, { id: 'buoyancy', name: 'Buoyancy', subtitle: 'Archimedes principle', symbol: '↑' }, { id: 'spring', name: 'Spring & SHM', subtitle: 'Oscillation and energy', symbol: '∿' }, { id: 'pendulum', name: 'Pendulum', subtitle: 'Nonlinear motion', symbol: '◌' }]
export const materials = [{ name: 'Aluminum', density: 2700 }, { name: 'Oak', density: 700 }, { name: 'Cork', density: 240 }, { name: 'Copper', density: 8960 }]
